import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Modal from "./components/modals/Modal";
import LoginModal from "./components/modals/LoginModal";
import SignUpModal from "./components/modals/SignUpModal";

export const metadata: Metadata = {
  title: "DjangoBnb",
  description: "Generated by create next app",
};

const inter = Inter ({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <LoginModal />
        <SignUpModal />
        <div className="pt-24">{children}</div>
      </body>
    </html>
  );
}
